on: push
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install build dependencies
      run: |-
        sudo apt-get update
        sudo apt-get install -y -o=Dpkg::Use-Pty=0 --no-install-recommends byacc cmake flex gcc gengetopt libc6-dev libgmp3-dev libjson-c-dev libpcap-dev libunistring-dev pkg-config
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |-
        mkdir build
        cd build
        cmake ..
        cmake --build .
        cpack -G TGZ -D CPACK_PACKAGE_FILE_NAME=zmap -D CPACK_INCLUDE_TOPLEVEL_DIRECTORY=OFF
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: build/zmap.tar.gz
        if-no-files-found: error
        retention-days: 1
